name: Gif

on: pull_request
jobs:
  dogs:
    runs-on: ubuntu-latest
    steps:
    - name: Doggoes as an Action
      uses: stanleynguyen/action-dogs@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
